# Generated by Django 3.1.5 on 2021-01-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pray_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('daily_pray', models.CharField(max_length=250)),
                ('booky', models.CharField(choices=[('john', 'john'), ('jacob', 'jacob'), ('james', 'james')], max_length=45)),
            ],
        ),
    ]
