# Generated by Django 3.1.5 on 2021-01-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pray_tb',
            name='booky',
            field=models.CharField(choices=[('john', 'john'), ('jacob', 'jacob'), ('james', 'james')], default='jacob', max_length=45),
        ),
    ]
