# Generated by Django 3.1.5 on 2021-01-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0002_auto_20210120_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pray_tb',
            name='daily_pray',
            field=models.TextField(max_length=250),
        ),
        migrations.CreateModel(
            name='more_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyp', models.TextField(max_length=250)),
                ('pray_tb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='praying.pray_tb')),
            ],
        ),
    ]
