# Generated by Django 3.1.5 on 2021-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0003_auto_20210121_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more_tb',
            name='dailyp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pray_tb',
            name='daily_pray',
            field=models.TextField(),
        ),
    ]
