# Generated by Django 3.1.5 on 2021-01-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0004_auto_20210121_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='pray_tb',
            name='img',
            field=models.ImageField(default=0, upload_to='pic'),
            preserve_default=False,
        ),
    ]
