# Generated by Django 3.1.5 on 2021-01-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0005_pray_tb_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pray_tb',
            name='posted_by',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
