# Generated by Django 3.1.5 on 2021-01-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0006_pray_tb_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='more_tb',
            old_name='dailyp',
            new_name='daily_prayer_desc',
        ),
        migrations.RenameField(
            model_name='pray_tb',
            old_name='booky',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='pray_tb',
            old_name='daily_pray',
            new_name='daily_prayer',
        ),
    ]
