# Generated by Django 3.1.5 on 2021-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0007_auto_20210123_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pray_tb',
            old_name='daily_prayer',
            new_name='Adhola_Prayer',
        ),
        migrations.RenameField(
            model_name='pray_tb',
            old_name='book',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='pray_tb',
            old_name='date_created',
            new_name='Date_Created',
        ),
        migrations.RenameField(
            model_name='pray_tb',
            old_name='posted_by',
            new_name='Posted_by',
        ),
        migrations.AddField(
            model_name='pray_tb',
            name='English_Prayer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
