# Generated by Django 3.1.5 on 2021-01-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0010_auto_20210124_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pray_tb',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
