# Generated by Django 3.1.5 on 2021-01-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0012_remove_pray_tb_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pray_tb',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
