# Generated by Django 3.1.5 on 2021-01-26 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0013_pray_tb_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pray_tb',
            name='Date_Created',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pray_tb',
            name='slug',
            field=models.SlugField(default=0, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
