# Generated by Django 3.1.5 on 2021-01-26 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0014_auto_20210126_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
