# Generated by Django 3.2.4 on 2021-06-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praying', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pray_tb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
